### ISSUE TITLE
Maybe need add debug toolbar in class Development(Common) ?

### ISSUE THREAD

**Issue by lov3catch** [jpadilla/django-project-template#11]
django-configurations version 2.0, using configuration 'Development'
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE_CLASSES.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE_CLASSES.

**Comment by chidg** [comment]
I did this: 
    
    class Development(Common):
        MIDDLEWARE_CLASSES = Common.MIDDLEWARE_CLASSES + ['debug_toolbar.middleware.DebugToolbarMiddleware']

**Comment by jpadilla** [comment]
Thanks!
