### ISSUE TITLE
With Whitenoise

### ISSUE THREAD

**Issue by julienkosinski** [jpadilla/django-project-template#5]
Hello,

I want to serve my staticfiles with whitenoise on heroku. When I implement it just like that : https://devcenter.heroku.com/articles/django-assets
I have this complete trace : 
http://pastebin.com/r7iCXVwu

And, here the complete settings :
http://pastebin.com/DYX89Q3k

What should I do ?
I just want to serve statics in heroku.

Thank you :).

**Comment by jpadilla** [comment]
@julienkosinski how does your `wsgi.py` look?

**Comment by julienkosinski** [comment]
Hello,

With Whitenoise, like this : http://pastebin.com/Uq3y8p0h

Thank you :).

**Comment by jpadilla** [comment]
@julienkosinski it's different to [wsgi.py](https://github.com/jpadilla/django-project-template/blob/master/project_name/wsgi.py).

Notice `from configurations.wsgi import get_wsgi_application` instead of `from django.core.wsgi import get_wsgi_application`.
